---
kind: pipeline
type: docker
name: planetposen-mail build and publish

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang
    commands:
      - make build

  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/planetposen-mail
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags: latest
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - master
